module.exports = {
  compatibilityVersion: '2.8.0',
  docsUrl: 'https://scummvm.org/compatibility/',
  gameIds: [
    [`007: James Bond - The Stealth Affair`, `cine:os`],
    [`Cruise for a Corpse`, `cruise:cruise`],
    [`Future Wars: Adventures in Time`, `cine:fw`],
    [`ADRIFT Interactive Fiction games`, `glk:adrift`],
    [`AGT Interactive Fiction games`, `glk:agt`],
    [`AdvSys Interactive Fiction games`, `glk:advsys`],
    [`Alan 2 & 3 Interactive Fiction games`, `glk:alan`],
    [`Archetype Interactive Fiction games`, `glk:archetype`],
    [`Glulx Interactive Fiction games`, `glk:glulx`],
    [`Hugo Interactive Fiction games`, `glk:hugo`],
    [`JACL Interactive Fiction games`, `glk:jacl`],
    [`Level 9 Interactive Fiction games`, `glk:level9`],
    [`Quest Interactive Fiction games`, `glk:quest`],
    [`Scott Adams Interactive Fiction games`, `glk:scottadams`],
    [`ZCode (Infocom and Inform) Interactive Fiction games`, `glk:zcode`],
    [`Adibou 1`, `gob:adibou1`],
    [`Adibou 2`, `gob:adibou2`],
    [`Bargon Attack`, `gob:bargon`],
    [`Croustibat`, `gob:crousti`],
    [`Fascination`, `gob:fascination`],
    [`Geisha`, `gob:geisha`],
    [`Gobliiins`, `gob:gob1`],
    [`Gobliins 2: The Prince Buffoon`, `gob:gob2`],
    [`Goblins Quest 3`, `gob:gob3`],
    [`Lost in Time`, `gob:lit`],
    [`Once Upon A Time: Little Red Riding Hood`, `gob:littlered`],
    [`Playtoons Limited Edition - Bambou le sauveur de la jungle`, `gob:bambou`],
    [`The Bizarre Adventures of Woodruff and the Schnibble`, `gob:woodruff`],
    [`Urban Runner`, `gob:urban`],
    [`Ween: The Prophecy`, `gob:ween`],
    [`Adventure Game Studio games`, `ags:ags`],
    [`Fukuoka Go-Round`, `director:fukuokagoround`],
    [`The Cute Machine`, `director:cutemachine`],
    [`Aesop's Fables: The Tortoise and the Hare`, `mohawk:tortoise`],
    [`Arthur's Birthday`, `mohawk:arthurbday`],
    [`Dr. Seuss's ABC`, `mohawk:seussabc`],
    [`Green Eggs and Ham`, `mohawk:greeneggs`],
    [`Harry and the Haunted House`, `mohawk:harryhh`],
    [`Just Grandma and Me`, `mohawk:grandma`],
    [`Little Monster at School`, `mohawk:lilmonster`],
    [`Marc Brown's Arthur's Teacher Trouble`, `mohawk:arthur`],
    [`Ruff's Bone`, `mohawk:ruff`],
    [`Sheila Rae, the Brave`, `mohawk:sheila`],
    [`The Berenstain Bears Get in a Fight`, `mohawk:bearfight`],
    [`The Berenstain Bears In The Dark`, `mohawk:beardark`],
    [`The New Kid on the Block`, `mohawk:newkid`],
    [`Alice: An Interactive Museum`, `director:alice`],
    [`Gadget: Invention, Travel and Adventure`, `director:gadget`],
    [`L-ZONE`, `director:lzone`],
    [`Ashina: The Red Witch`, `ags:ashinaredwitch`],
    [`Just Ignore Them`, `ags:justignorethem`],
    [`My Big Sister`, `ags:mybigsister`],
    [`My Big Sister Remastered`, `ags:mybigsisterrm`],
    [`Red Bow`, `ags:redbow`],
    [`Astro Chicken`, `sci:astrochicken`],
    [`Castle of Dr. Brain`, `sci:castlebrain`],
    [`Code-Name: Iceman`, `sci:iceman`],
    [`Conquests of Camelot: The Search for the Grail`, `sci:camelot`],
    [`Conquests of the Longbow: The Legend of Robin Hood`, `sci:longbow`],
    [`Donald Duck's Playground`, `agi:ddp`],
    [`EcoQuest II: Lost Secret of the Rainforest`, `sci:ecoquest2`],
    [`EcoQuest: The Search for Cetus`, `sci:ecoquest`],
    [`Freddy Pharkas: Frontier Pharmacist`, `sci:freddypharkas`],
    [`Gabriel Knight: Sins of the Fathers`, `sci:gk1`],
    [`Gold Rush`, `agi:goldrush`],
    [`Hi-Res Adventure #0: Mission Asteroid`, `adl:hires0`],
    [`Hi-Res Adventure #1: Mystery House`, `adl:hires1`],
    [`Hi-Res Adventure #2: The Wizard and the Princess`, `adl:hires2`],
    [`Hi-Res Adventure #3: Cranston Manor`, `adl:hires3`],
    [`Hi-Res Adventure #4: Ulysses and the Golden Fleece`, `adl:hires4`],
    [`Hi-Res Adventure #5: Time Zone`, `adl:hires5`],
    [`Hi-Res Adventure #6: The Dark Crystal`, `adl:hires6`],
    [`Hoyle Classic Card Games`, `sci:hoyle4`],
    [`Hoyle Classic Games`, `sci:hoyle5`],
    [`Hoyle Solitaire`, `sci:hoyle5solitaire`],
    [`Hoyle's Official Book of Games: Volume 1`, `sci:hoyle1`],
    [`Hoyle's Official Book of Games: Volume 2`, `sci:hoyle2`],
    [`Hoyle's Official Book of Games: Volume 3`, `sci:hoyle3`],
    [`Inside the Chest`, `sci:chest`],
    [`Jones in the Fast Lane`, `sci:jones`],
    [`King's Quest I: Quest for the Crown`, `agi:kq1`],
    [`King's Quest II: Romancing the Throne`, `agi:kq2`],
    [`King's Quest III: To Heir Is Human`, `agi:kq3`],
    [`King's Quest IV: The Perils of Rosella`, `agi:kq4`],
    [`King's Quest IV: The Perils of Rosella`, `sci:kq4sci`],
    [`King's Quest V: Absence Makes the Heart Go Yonder`, `sci:kq5`],
    [`King's Quest VI: Heir Today, Gone Tomorrow`, `sci:kq6`],
    [`King's Quest VII: The Princeless Bride`, `sci:kq7`],
    [`King's Quest: Quest for the Crown`, `sci:kq1sci`],
    [`King's Questions`, `sci:kquestions`],
    [`Laura Bow 2: The Dagger of Amon Ra`, `sci:laurabow2`],
    [`Laura Bow: The Colonel's Bequest`, `sci:laurabow`],
    [`Leisure Suit Larry 2: Goes Looking for Love (in Several Wrong Places`, `sci:lsl2`],
    [`Leisure Suit Larry 3: Passionate Patti in Pursuit of the Pulsating Pectorals`, `sci:lsl3`],
    [`Leisure Suit Larry 5: Passionate Patti Does a Little Undercover Work`, `sci:lsl5`],
    [`Leisure Suit Larry 6: Shape Up or Slip Out`, `sci:lsl6`],
    [`Leisure Suit Larry 6: Shape Up or Slip Out`, `sci:lsl6hires`],
    [`Leisure Suit Larry 7: Love for Sail`, `sci:lsl7`],
    [`Leisure Suit Larry in the Land of the Lounge Lizards`, `agi:lsl1`],
    [`Leisure Suit Larry in the Land of the Lounge Lizards`, `sci:lsl1sci`],
    [`Lighthouse: The Dark Being`, `sci:lighthouse`],
    [`Manhunter 2: San Francisco`, `agi:mh2`],
    [`Manhunter: New York`, `agi:mh1`],
    [`Mickey's Space Adventure`, `agi:mickey`],
    [`Mixed Up Fairy Tales`, `sci:fairytales`],
    [`Mixed-Up Mother Goose`, `agi:mixedup`],
    [`Mixed-Up Mother Goose`, `sci:mothergoose`],
    [`Mixed-Up Mother Goose`, `sci:mothergoose256`],
    [`Mixed-Up Mother Goose Deluxe`, `sci:mothergoosehires`],
    [`Pepper's Adventures in Time`, `sci:pepper`],
    [`Phantasmagoria`, `sci:phantasmagoria`],
    [`Phantasmagoria 2: A Puzzle of Flesh`, `sci:phantasmagoria2`],
    [`Police Quest 2: The Vengeance`, `sci:pq2`],
    [`Police Quest 3: The Kindred`, `sci:pq3`],
    [`Police Quest IV: Open Season`, `sci:pq4`],
    [`Police Quest: In Pursuit of the Death Angel`, `agi:pq1`],
    [`Police Quest: In Pursuit of the Death Angel`, `sci:pq1sci`],
    [`Police Quest: SWAT`, `sci:pqswat`],
    [`Quest for Glory I: So You Want To Be A Hero`, `sci:qfg1`],
    [`Quest for Glory I: So You Want To Be A Hero`, `sci:qfg1vga`],
    [`Quest for Glory II: Trial by Fire`, `sci:qfg2`],
    [`Quest for Glory III: Wages of War`, `sci:qfg3`],
    [`Quest for Glory IV: Shadows of Darkness`, `sci:qfg4`],
    [`RAMA`, `sci:rama`],
    [`Shivers`, `sci:shivers`],
    [`Slater & Charlie Go Camping`, `sci:slater`],
    [`Space Quest 6: Roger Wilco in the Spinal Frontier`, `sci:sq6`],
    [`Space Quest I: Roger Wilco in the Sarien Encounter`, `sci:sq1sci`],
    [`Space Quest II: Chapter II - Vohaul's Revenge`, `agi:sq2`],
    [`Space Quest III: The Pirates of Pestulon`, `sci:sq3`],
    [`Space Quest IV: Roger Wilco and the Time Rippers`, `sci:sq4`],
    [`Space Quest V: The Next Mutation`, `sci:sq5`],
    [`Space Quest: Chapter I - The Sarien Encounter`, `agi:sq1`],
    [`The Beast Within: A Gabriel Knight Mystery`, `sci:gk2`],
    [`The Black Cauldron`, `agi:bc`],
    [`The Island of Dr. Brain`, `sci:islandbrain`],
    [`Torin's Passage`, `sci:torin`],
    [`Troll's Tale`, `agi:troll`],
    [`Winnie the Pooh in the Hundred Acre Wood`, `agi:winnie`],
    [`Backyard Baseball`, `scumm:baseball`],
    [`Backyard Baseball 2001`, `scumm:baseball2001`],
    [`Backyard Baseball 2003`, `scumm:baseball2003`],
    [`Backyard Football`, `scumm:football`],
    [`Backyard Football 2002`, `scumm:football2002`],
    [`Bear Stormin`, `scumm:brstorm`],
    [`Big Thinkers! 1st Grade`, `scumm:thinker1`],
    [`Big Thinkers! Kindergarten`, `scumm:thinkerk`],
    [`Blue's 123 Time Activities`, `scumm:blues123time`],
    [`Blue's ABC Time Activities`, `scumm:bluesabctime`],
    [`Blue's Clues: Blue's Art Time Activities`, `scumm:arttime`],
    [`Blue's Clues: Blue's Birthday Adventure`, `scumm:bluesbirthday`],
    [`Blue's Reading Time Activities`, `scumm:readtime`],
    [`Blue's Treasure Hunt`, `scumm:bluestreasurehunt`],
    [`Fatty Bear's Birthday Surprise`, `scumm:fbear`],
    [`Fatty Bear's FunPack`, `scumm:fbpack`],
    [`Freddi Fish 2: The Case of the Haunted Schoolhouse`, `scumm:freddi2`],
    [`Freddi Fish 3: The Case of the Stolen Conch Shell`, `scumm:freddi3`],
    [`Freddi Fish 4: The Case of the Hogfish Rustlers of Briny Gulch`, `scumm:freddi4`],
    [`Freddi Fish 5: The Case of the Creature of Coral Cove`, `scumm:freddicove`],
    [`Freddi Fish and Luther's Maze Madness`, `scumm:maze`],
    [`Freddi Fish and Luther's Water Worries`, `scumm:water`],
    [`Freddi Fish and the Case of the Missing Kelp Seeds`, `scumm:freddi`],
    [`Let's Explore the Airport`, `scumm:airport`],
    [`Let's Explore the Farm`, `scumm:farm`],
    [`Let's Explore the Jungle`, `scumm:jungle`],
    [`Pajama Sam 2: Thunder and Lightning Aren't so Frightening`, `scumm:pajama2`],
    [`Pajama Sam 3: You Are What You Eat From Your Head To Your Feet`, `scumm:pajama3`],
    [`Pajama Sam's Lost & Found`, `scumm:lost`],
    [`Pajama Sam's Sock Works`, `scumm:socks`],
    [`Pajama Sam: Games to Play on Any Day`, `scumm:pjgames`],
    [`Pajama Sam: No Need to Hide When It's Dark Outside`, `scumm:pajama`],
    [`Putt-Putt Enters the Race`, `scumm:puttrace`],
    [`Putt-Putt Goes to the Moon`, `scumm:puttmoon`],
    [`Putt-Putt Joins the Circus`, `scumm:puttcircus`],
    [`Putt-Putt Joins the Parade`, `scumm:puttputt`],
    [`Putt-Putt Saves the Zoo`, `scumm:puttzoo`],
    [`Putt-Putt Travels Through Time`, `scumm:putttime`],
    [`Putt-Putt and Fatty Bear's Activity Pack`, `scumm:activity`],
    [`Putt-Putt and Pep's Balloon-O-Rama`, `scumm:balloon`],
    [`Putt-Putt and Pep's Dog on a Stick`, `scumm:dog`],
    [`Putt-Putt's Fun Pack`, `scumm:funpack`],
    [`SPY Fox in "Cheese Chase`, `scumm:chase`],
    [`Spy Fox 2: "Some Assembly Required`, `scumm:spyfox2`],
    [`Spy Fox in "Dry Cereal`, `scumm:spyfox`],
    [`Spy Fox in "Hold the Mustard`, `scumm:mustard`],
    [`Spy Fox: "Operation Ozone`, `scumm:spyozon`],
    [`Beneath a Steel Sky`, `sky:sky`],
    [`Broken Sword II: The Smoking Mirror`, `sword2:sword2`],
    [`Broken Sword: The Shadow of the Templars`, `sword1:sword1`],
    [`Lure of the Temptress`, `lure:lure`],
    [`Blackwell Unbound`, `ags:blackwell2`],
    [`Da New Guys: Day of the Jackass`, `ags:danewguys2`],
    [`Gemini Rue`, `ags:geminirue`],
    [`Shardlight`, `ags:shardlight`],
    [`The Blackwell Convergence`, `ags:blackwell3`],
    [`The Blackwell Deception`, `ags:blackwell4`],
    [`The Blackwell Epiphany`, `ags:blackwell5`],
    [`The Blackwell Legacy`, `ags:blackwell1`],
    [`The Shivah`, `ags:shivah`],
    [`The Shivah: Kosher Edition`, `ags:shivahkosher`],
    [`Unavowed`, `ags:unavowed`],
    [`Blade Runner`, `bladerunner:bladerunner`],
    [`Eye of the Beholder`, `kyra:eob`],
    [`Eye of the Beholder II: The Legend of Darkmoon`, `kyra:eob2`],
    [`Lands of Lore: The Throne of Chaos`, `kyra:lol`],
    [`The Legend of Kyrandia`, `kyra:kyra1`],
    [`The Legend of Kyrandia: Book 3 - Malcolm's Revenge`, `kyra:kyra3`],
    [`The Legend of Kyrandia: Hand of Fate`, `kyra:kyra2`],
    [`Blue Force`, `tsage:blueforce`],
    [`Return to Ringworld`, `tsage:ringworld2`],
    [`Ringworld: Revenge of the Patriarch`, `tsage:ringworld`],
    [`Clandestiny`, `groovie:clandestiny`],
    [`The 11th Hour: The Sequel to The 7th Guest`, `groovie:11h`],
    [`The 7th Guest`, `groovie:t7g`],
    [`Uncle Henry's Playhouse`, `groovie:unclehenry`],
    [`Corruption`, `glk:corruption`],
    [`Fish`, `glk:fish`],
    [`Jinxter`, `glk:jinxter`],
    [`Myth`, `glk:myth`],
    [`The Guild of Thieves`, `glk:guild`],
    [`The Pawn`, `glk:pawn`],
    [`Wonderland`, `glk:wonderland`],
    [`Crusader: No Remorse`, `ultima:remorse`],
    [`Ultima IV: Quest of the Avatar`, `ultima:ultima4`],
    [`Ultima VI: The False Prophet`, `ultima:ultima6`],
    [`Ultima VIII - Pagan`, `ultima:ultima8`],
    [`Darby the Dragon`, `composer:darby`],
    [`Gregory and the Hot Air Balloon`, `composer:gregory`],
    [`Magic Tales: Baba Yaga and the Magic Geese`, `composer:babayaga`],
    [`Magic Tales: Imo & the King`, `composer:imoking`],
    [`Magic Tales: Liam Finds a Story`, `composer:liam`],
    [`Magic Tales: Sleeping Cub's Test of Courage`, `composer:sleepingcub`],
    [`Magic Tales: The Little Samurai`, `composer:littlesamurai`],
    [`Magic Tales: The Princess and the Crab`, `composer:princess`],
    [`Elvira II: The Jaws of Cerberus`, `agos:elvira2`],
    [`Elvira: Mistress of the Dark`, `agos:elvira1`],
    [`Personal Nightmare`, `agos:pn`],
    [`Simon the Sorcerer`, `agos:simon1`],
    [`Simon the Sorcerer II: The Lion, the Wizard and the Wardrobe`, `agos:simon2`],
    [`Simon the Sorcerer's Puzzle Pack: Demon in my Pocket`, `agos:dimp`],
    [`Simon the Sorcerer's Puzzle Pack: Jumble`, `agos:jumble`],
    [`Simon the Sorcerer's Puzzle Pack: NoPatience`, `agos:puzzle`],
    [`Simon the Sorcerer's Puzzle Pack: Swampy Adventures`, `agos:swampy`],
    [`The Feeble Files`, `agos:feeble`],
    [`Waxworks`, `agos:waxworks`],
    [`Escape From Monkey Island`, `grim:monkey4`],
    [`Full Throttle`, `scumm:ft`],
    [`Grim Fandango`, `grim:grim`],
    [`Indiana Jones and the Fate of Atlantis`, `scumm:atlantis`],
    [`Indiana Jones and the Last Crusade: The Graphic Adventure`, `scumm:indy3`],
    [`Loom`, `scumm:loom`],
    [`Maniac Mansion`, `scumm:maniac`],
    [`Maniac Mansion: Day of the Tentacle`, `scumm:tentacle`],
    [`Monkey Island 2: LeChuck's Revenge`, `scumm:monkey2`],
    [`Passport to Adventure (Indiana Jones and the Last Crusade, The Secret of Monkey Island, Loom`, `scumm:pass`],
    [`Sam & Max: Hit the Road`, `scumm:samnmax`],
    [`The Curse of Monkey Island`, `scumm:comi`],
    [`The Dig`, `scumm:dig`],
    [`The Secret of Monkey Island`, `scumm:monkey`],
    [`Zak McKracken and the Alien Mindbenders`, `scumm:zak`],
    [`Escape from the Mansion`, `wintermute:escapemansion`],
    [`Maniac Mansion Deluxe`, `ags:maniacmansiondeluxe`],
    [`Space Quest Minus 1: Decisions of the Elders`, `ags:sqdote`],
    [`Space Quest: Incinerations`, `ags:sqinc`],
    [`The Griffon Legend`, `griffon:griffon`],
    [`Five Lethal Demons`, `wintermute:5ld`],
    [`Five Magical Amulets`, `wintermute:5ma`],
    [`Helga Deep In Trouble`, `wintermute:helga`],
    [`Football Game`, `ags:footballgame`],
    [`Sumatra: Fate of Yandi`, `ags:sumatra`],
    [`The Excavation of Hob's Barrow`, `ags:excavationhb`],
    [`Gobliiins5 - L'Invasion des Morglotons Part1	ags`, `gobliiins5-1`],
    [`Gobliiins5 - L'Invasion des Morglotons Part2	ags`, `gobliiins5-2`],
    [`Gobliiins5 - L'Invasion des Morglotons Part3	ags`, `gobliiins5-3`],
    [`Gobliiins5 - L'Invasion des Morglotons Part4	ags`, `gobliiins5-4`],
    [`Halls of the Dead: Faery Tale Adventure II`, `saga2:fta2`],
    [`Harlan Ellison: I Have No Mouth, and I Must Scream`, `saga:ihnm`],
    [`Inherit the Earth: Quest for the Orb`, `saga:ite`],
    [`Henachoco #1`, `director:henachoco01`],
    [`Henachoco #2`, `director:henachoco02`],
    [`Henachoco #3`, `director:henachoco03`],
    [`Henachoco #4`, `director:henachoco04`],
    [`Yaken Rodem`, `director:henachoco05`],
    [`Hugo II: Whodunit`, `hugo:hugo2`],
    [`Hugo III: Jungle of Doom`, `hugo:hugo3`],
    [`Hugo's House of Horrors`, `hugo:hugo1`],
    [`Might and Magic: Book One - Secret of the Inner Sanctum`, `mm:mm1`],
    [`Might and Magic: Clouds of Xeen`, `mm:cloudsofxeen`],
    [`Might and Magic: Darkside of Xeen`, `mm:darksideofxeen`],
    [`Might and Magic: Swords of Xeen`, `mm:swordsofxeen`],
    [`Might and Magic: World of Xeen`, `mm:worldofxeen`],
    [`Muppet Treasure Island`, `mtropolis:mti`],
    [`Return to Zork`, `made:rtz`],
    [`Zork Nemesis: The Forbidden Lands`, `zvision:znemesis`],
    [`Zork: Grand Inquisitor`, `zvision:zgi`],
    [`Myst`, `mohawk:myst`],
    [`Riven: The Sequel to Myst`, `mohawk:riven`],
    [`The Manhole`, `made:manhole`],
    [`Myst III: Exile`, `myst3:myst3`],
    [`The Journeyman Project 2: Buried in Time`, `buried:buried`],
    [`The Journeyman Project: Pegasus Prime`, `pegasus:pegasus`],
    [`Nancy Drew: Message in a Haunted Mansion`, `nancy:nancy3`],
    [`Nancy Drew: Secrets Can Kill`, `nancy:nancy1`],
    [`Nancy Drew: Stay Tuned for Danger`, `nancy:nancy2`],
    [`Nancy Drew: The Final Scene`, `nancy:nancy5`],
    [`Nancy Drew: Treasure in the Royal Tower`, `nancy:nancy4`],
    [`The Vampire Diaries`, `nancy:vampirediaries`],
    [`OO-Topos`, `glk:ootopos`],
    [`The Crimson Crown: Further Adventures in Transylvania`, `glk:crimsoncrown`],
    [`Transylvania`, `glk:transylvania`],
    [`Reah: Face the Unknown`, `vcruise:reah`],
    [`Schizm: Mysterious Journey`, `vcruise:schizm`],
    [`Sfinx`, `cge2:sfinx`],
    [`Sołtys`, `cge:soltys`],
    [`1½ Ritter: Auf der Suche nach der hinreißenden Herzelinde`, `wintermute:ritter`],
    [`3 Skulls of the Toltecs`, `toltecs:toltecs`],
    [`A Golden Wake`, `ags:goldenwake`],
    [`Amazon: Guardians of Eden`, `access:amazon`],
    [`Ape Odyssey 2001`, `director:apeodyssey`],
    [`Bickadoodle`, `wintermute:bickadoodle`],
    [`Blazing Dragons`, `dragons:dragons`],
    [`Broken Sword 2.5: The Return of the Templars`, `sword25:sword25`],
    [`Bud Tucker in Double Trouble`, `tucker:tucker`],
    [`Chewy: Esc from F5`, `chewy:chewy`],
    [`Chivalry is Not Dead`, `wintermute:chivalry`],
    [`Chop Suey`, `director:chopsuey`],
    [`Classical Cats`, `director:classicalcats`],
    [`Daniel in the Lions' Den`, `mohawk:daniel`],
    [`The Story of Creation`, `mohawk:create`],
    [`Dark Side`, `freescape:darkside`],
    [`Driller`, `freescape:driller`],
    [`Dead City`, `wintermute:deadcity`],
    [`Dirty Split`, `wintermute:dirtysplit`],
    [`Discworld`, `tinsel:dw`],
    [`Discworld II: Missing Presumed...!?`, `tinsel:dw2`],
    [`Dragon History`, `draci:draci`],
    [`DreamWeb`, `dreamweb:dreamweb`],
    [`Dreams in the Witch House`, `ags:dreamswitchhouse`],
    [`Dráscula: The Vampire Strikes Back`, `drascula:drascula`],
    [`Duckman: The Graphic Adventures of a Private Dick`, `illusions:duckman`],
    [`Eastern Mind`, `director:easternmind`],
    [`The Seven Colors: Legend of PSY・S City`, `director:the7colors`],
    [`Escape From Hell`, `efh:efh`],
    [`Flight of the Amazon Queen`, `queen:queen`],
    [`Full Pipe`, `ngi:fullpipe`],
    [`Ganbare! Inuchan: Rock'n Roll Edition`, `director:ganbareinuchan`],
    [`Nemurenu Yoru no Chiisana O-Hanashi`, `director:nemurenu`],
    [`Ganbare! Inuchan: Trip Around the World`, `director:ganbareinuchan2`],
    [`Hades Challenge`, `hadesch:hadesch`],
    [`Hopkins FBI`, `hopkins:hopkins`],
    [`Hyperspace Delivery Boy`, `hdb:hdb`],
    [`Japan Art Today 07: Takashi Murakami - A Romantic Evening`, `director:japanart07`],
    [`Kathy Rain`, `ags:kathyrain`],
    [`Whispers of a Machine`, `ags:whispersofamachine`],
    [`Kingdom: The Far Reaches`, `kingdom:kingdom`],
    [`Leather Goddesses of Phobos! 2: Gas Pump Girls Meet the Pulsating Inconvenience from Planet X`, `made:lgop2`],
    [`Little Big Adventure (Relentless: Twinsen's Adventure`, `twine:lba`],
    [`MTV's Beavis and Butt-Head in Virtual Stupidity`, `bbvs:bbvs`],
    [`Majestic Part 1: Alien Encounter`, `director:majestic`],
    [`Marvel Comics Spider-Man: The Sinister Six`, `hypno:sinistersix`],
    [`Private Eye	private`, `private-eye`],
    [`Mission Supernova 1`, `supernova:msn1`],
    [`Mission Supernova 2`, `supernova:msn2`],
    [`Mortville Manor`, `mortevielle:mortevielle`],
    [`Nightlong: Union City Conspiracy`, `trecision:nl`],
    [`Nippon Safes, Inc`, `parallaction:nippon`],
    [`Obsidian`, `mtropolis:obsidian`],
    [`Orion Burger`, `m4:burger`],
    [`Over-Ring-Under`, `director:overringunder`],
    [`Plumbers Don't Wear Ties`, `plumbers:plumbers`],
    [`Primordia`, `ags:primordia`],
    [`Strangeland`, `ags:strangeland`],
    [`Red Comrades 1: Save the Galaxy`, `petka:petka1`],
    [`Red Comrades 2: For the Great Justice`, `petka:petka2`],
    [`Resonance`, `ags:resonance`],
    [`Rex Nebular and the Cosmic Gender Bender`, `mads:nebular`],
    [`Rodney's Funscreen`, `made:rodney`],
    [`Rosemary`, `wintermute:rosemary`],
    [`Sanitarium`, `asylum:sanitarium`],
    [`Soldier Boyz`, `hypno:soldierboyz`],
    [`Wetlands`, `hypno:wetlands`],
    [`Space Quest IV.5 - Roger Wilco and the Voyage Home`, `ags:sq45`],
    [`Space Quest: Vohaul Strikes Back`, `ags:sqvsb`],
    [`Spaceship Warlock`, `director:warlock`],
    [`Starship Titanic`, `titanic:titanic`],
    [`Stellaluna`, `mohawk:stellaluna`],
    [`Syberia`, `tetraedge:syberia`],
    [`Syberia II`, `tetraedge:syberia2`],
    [`Technobabylon`, `ags:technobabylon`],
    [`Teen Agent`, `teenagent:teenagent`],
    [`The Prince and the Coward`, `prince:prince`],
    [`Tender Loving Care`, `groovie:tlc`],
    [`The Better Dead Ratification`, `director:betterd`],
    [`The Dark Eye`, `director:darkeye`],
    [`The Labyrinth of Time`, `lab:lab`],
    [`The Longest Journey`, `stark:tlj`],
    [`The Lost Files of Sherlock Holmes: Case of the Rose Tattoo`, `sherlock:rosetattoo`],
    [`The Lost Files of Sherlock Holmes: The Case of the Serrated Scalpel`, `sherlock:scalpel`],
    [`The Neverhood`, `neverhood:neverhood`],
    [`The Pink Panther: Hokus Pokus Pink`, `pink:pokus`],
    [`The Pink Panther: Passport to Peril`, `pink:peril`],
    [`The White Chamber`, `wintermute:twc`],
    [`Time Gal`, `director:timegal`],
    [`Tony Tough and the Night of Roasted Moths`, `tony:tony`],
    [`Toonstruck`, `toon:toon`],
    [`Touché: The Adventures of the Fifth Musketeer`, `touche:touche`],
    [`U.F.O.s`, `gnap:gnap`],
    [`Valmaison au fil des saisons / Pepperon`, `director:pepperon`],
    [`Versailles 1685`, `cryomni3d:versailles`],
    [`Voyeur`, `voyeur:voyeur`],
    [`Wrath of the Gods`, `director:wrath`],
  ]
}
